### ISSUE TITLE
Implement save/load

### ISSUE THREAD

**Issue by denis-angilella** [KenanHanke/rbloom#1]
Hello,
I made a small benchmark and rBloom is about 2x faster than [pybloomfiltermmap3](https://github.com/prashnts/pybloomfiltermmap3), wow!

Would it be possible to save filter bits to a file and reload it?
Access to bits from Python and a new arg in Bloom.new() can be sufficient.

Thanks!
Denis

**Comment by KenanHanke** [comment]
Hi,

In principle, it would be easy to just implement a `save(self, file_path)` instance method and a `load(cls, file_path) -> Bloom` classmethod, but the problem is that by default, Python's built-in hash uses a [random salt that changes with every run](https://docs.python.org/3/reference/datamodel.html?highlight=__hash__#object.__hash__). Ints are currently hashed to themselves, and float hashes seem to be stable, but everything else changes, and no guarantees are made about the future.

This random salting can be disabled with an [environment variable](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONHASHSEED), but there are still no guarantees about anything staying stable across platforms and versions.

So given all that, what kind of architecture would you suggest? The only safe thing I can come up with is maybe adding a "savable" or "persistable" flag to the constructor, which would disable adding anything other than `int` objects to that Bloom filter object but enable the aforementioned `save(self, path)` method.

Ken

**Comment by denis-angilella** [comment]
Hi,

Thank you for the explanation @kenbyte !

The save/load mechanism may be enabled only if a `hash_func` is provided and fail when using the default built-in Python hash.
This moves the responsibility of using a deterministic hash function to the user and should be documented.

What do you think of this option?

Denis

**Comment by KenanHanke** [comment]
Sounds good to me, will implement in the next few days :)

**Comment by KenanHanke** [comment]
Update: Might take slightly longer because I'd like to merge #3 first to avoid unnecessary complication

**Comment by denis-angilella** [comment]
Thanks for the update. There is no hurry
The changes in #3 looks great

**Comment by KenanHanke** [comment]
I have now implemented persistence; see the readme for how to use it!

**Comment by denis-angilella** [comment]
Great! Thank you
