### ISSUE TITLE
add properties for 'expected_number_of_items' and 'false_positive_rate'

### ISSUE THREAD

**Issue by phrrngtn** [KenanHanke/rbloom#10]
Hi,
I have had great fun lifting rbloom in Excel UDFs (via PyXLL). It was very straightforward and although I have not benchmarked it is working well for the kind of data-sets I have in mind. One thing that came up is that it would be very nice to have accessors for the values used for `expected_number_of_items` and `false_positive_rate` in the constructor.  I realize I can do this via subclassing but thought I would suggest the feature to you in any case.

My use case is when opening a workbook, to be able to load up filter contents from a blob of data (base64-encoded, lzma-compressed dump of a filter) and thus need to know what values to pass in to the constructor. I would like to box the entire thing as a JSON dict with keys of `expected_number_of_items`, `false_positive_rate` and `blob` (I am using `mmh3_signed_128bit` as a hardwired hash func). Note that one use-case is to generate and serialize the filter outside of Excel so it would not be possible for me to pick up from the worksheet the values used to construct the filter. 

I have not written anything in Rust yet so am solving my immediate needs via a Python wrapper class.

thanks in advance,
pjjH

**Comment by KenanHanke** [comment]
Hey there, and thank you for your interest in rBloom!

The values used for ```expected_number_of_items``` and ```false_positive_rate``` aren't actually ever saved anywhere, but instead just used during initialization of the object in order to calculate the byte size of the filter and the necessary number of integers (indexes) to distribute the hash's entropy over. Saving them by default would be unnecessary for filter operation and would break backwards compatibility with filters saved by previous rBloom versions. For that reason, I don't see any reasonable path forwards with that feature.

If you're just loading a saved filter, you might not even need to save ```expected_number_of_items``` and ```false_positive_rate```; it might be enough to use ```filter.save_bytes()``` and ```Bloom.load_bytes(blob, hash_func)```. And if you do, subclassing does sound like an excellent way forward.

In any case, thank you for your suggestion and I hope you get lots of utility from rBloom in the future!
