### ISSUE TITLE
Saving and loading bloom filters of ints

### ISSUE THREAD

**Issue by CalebFenton** [KenanHanke/rbloom#13]
Sometimes I need to know if an int is in my big pile of billions of ints. I really like this library, but it doesn't seem like I can save the bloom filter if it's only ints (default hash function). This seems like it would be the most simple use case which makes me think I'm doing something wrong.

> Cannot save a bloom filter that uses the built-in hash function

Is this functionality supported? Is this a dumb question?

The work around would be: cast the ints to a bytes array or a string or something and use mmh or something as a fast hash function.

Thanks for the solid library

**Comment by CalebFenton** [comment]
I think I found a perfectly fine "work-around" and that's to define an ultra simple hash function of `lambda x: x`. I'm making a bloom filter out of hash values stored as integers so no need to hash it again. This seems to work.

**Comment by KenanHanke** [comment]
Hi, the built-in hash function has a different salt upon each invocation of Python, which is why saving anything resulting from it would be pointless. Using `lambda x: x` will work for all ints within the range of a signed 128 bit int as you can see from the documentation. If you have any ints outside that range, it will probably still work correctly as long as you didn't compile rbloom in debug mode (Rust checks for stuff that's out of bounds when compiled in debug mode), but I would recommend using something like `lambda x: (x + (1 << 127)) % (1 << 128) - (1 << 127)` to be safe, which is the fastest way I can come up with to cast an int into that range within Python. It is around 3.5 times slower than `lambda x: x` though
